In [19]:
import numpy
import pandas

field = ['SOURCE', 'TARGET', 'RATING', 'TIME']

a = numpy.matrix([
    [0,0,0,0,0,0],
    [1,0,1/3,1/3,1/4,0],
    [0,1/3,0,1/3,1/4,0],
    [0,1/3,1/3,0,1/4,0],
    [0,1/3,1/3,1/3,0,0],
    [0,0,0,0,1/4,0]
])

b = (1/6) * numpy.matrix([[1]*6]*6)

m = 0.85*a + 0.15*b

v = (1/6) * numpy.matrix([[1] for i in range(6)])

count = 0

def pagehank(v):
    global count
    if sum(abs(m*v-v)) > 0.001:
        count +=1
        return pagehank(m*v)
    else:
        count += 1
        return m*v
    

result = pagehank(v)

sorted(result, reverse=True)

[matrix([[ 0.00316083]]),
 matrix([[ 0.003088]]),
 matrix([[ 0.00290815]]),
 matrix([[ 0.00290815]]),
 matrix([[ 0.00106494]]),
 matrix([[ 0.00036155]])]

In [26]:
a = pandas.read_csv("soc-sign-bitcoinotc.csv")
a = numpy.matrix(a)

heigth, width = a.shape

b = (1/6) * numpy.matrix([[1]*width]*heigth)

m = 0.85*a + 0.15*b

v = (1/6) * numpy.matrix([[1] for i in range(heigth)])

result = pagehank(v)

sorted(result, reverse=True)

[[  6.00000000e+00   5.00000000e+00   2.00000000e+00   1.28924194e+09]
 [  1.00000000e+00   1.50000000e+01   1.00000000e+00   1.28924314e+09]
 [  4.00000000e+00   3.00000000e+00   7.00000000e+00   1.28924528e+09]
 ..., 
 [  2.73100000e+03   4.89700000e+03   5.00000000e+00   1.45367943e+09]
 [  1.30000000e+01   1.12800000e+03   1.00000000e+00   1.45367963e+09]
 [  1.12800000e+03   1.30000000e+01   2.00000000e+00   1.45368432e+09]]
