In [1]:
import numpy
import pandas

a = numpy.matrix([
    [0,0,0,0,0,0],
    [1,0,1/3,1/3,1/4,0],
    [0,1/3,0,1/3,1/4,0],
    [0,1/3,1/3,0,1/4,0],
    [0,1/3,1/3,1/3,0,0],
    [0,0,0,0,1/4,0]
])

b = (1/6) * numpy.matrix([[1]*6]*6)

m = 0.85*a + 0.15*b

v = (1/6) * numpy.matrix([[1] for i in range(6)])

count = 0

def pagehank(v):
    global count
    if sum(abs(m*v-v)) > 0.001:
        count +=1
        return pagehank(m*v)
    else:
        count += 1
        return m*v
    

result = pagehank(v)

sorted(result, reverse=True)

[matrix([[ 0.00316083]]),
 matrix([[ 0.003088]]),
 matrix([[ 0.00290815]]),
 matrix([[ 0.00290815]]),
 matrix([[ 0.00106494]]),
 matrix([[ 0.00036155]])]

In [2]:
data = pandas.read_csv("soc-sign-bitcoinotc.csv", names=['source', 'target', 'rating', 'time'])

data = data[data.rating>=8]

In [6]:
def get_index(data):
    index = {}
    for source, target, rating in zip(data.source, data.target, data.rating):
        if source in index.keys():
            index[source].append(target)
        else:
            index[source] = [target]
            
        if not target in index.keys(): index[target] = []

    return index

def to_matrix(matrix):
    aux = []
    keys = list(matrix.keys())
    size = len(keys)
    for i in range(size):
        line = [0 for i in range(len(keys))]
        if len(matrix[keys[i]]) == 0:
            line = [1/size for i in range(size)]
        for j in matrix[keys[i]]:
            line[keys.index(j)] = 1 / len(matrix[keys[i]])
        aux.append(line)
    return aux

matrix = numpy.matrix(to_matrix(get_index(data)))

size = len(matrix)

b = (1/size) * numpy.matrix([[1]*size]*size)

m = 0.85*matrix + 0.15*b

v = (1/size) * numpy.matrix([[1] for i in range(size)])


count = 0

def pagehank(v):
    global count
    if sum(abs(m*v-v)) > 0.001:
        print("count", count)
        count +=1
        print("sum(abs(m*v-v))", sum(abs(m*v-v)))
        return pagehank(m*v)
    else:
        count += 1
        return m*v

result = pagehank(v)

sorted(result, reverse=True)

opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa
opa


[matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),
 matrix([[ 0.0010929]]),


In [8]:
matrix[0]

matrix([[ 0. ,  0.2,  0.2,  0. ,  0.2,  0. ,  0.2,  0. ,  0. ,  0. ,  0. ,
          0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
          0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
          0.2,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
          0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
          0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
          0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
          0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
          0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
          0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
          0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
          0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
          0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
          0. ,  0. ,  0. 